---
openapi: 3.0.1
info:
  title: TRELLO API VERSION 1
  version: v1
paths:
  "/api/v1/boards":
    get:
      summary: Retrieve the boards
      tags:
      - Boards
      responses:
        '200':
          description: boards retrieved
    post:
      summary: Creates a board
      tags:
      - Boards
      parameters: []
      responses:
        '200':
          description: successful
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
              required:
              - name
  "/api/v1/boards/{id}":
    get:
      summary: Retrieve a board
      tags:
      - Boards
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: board found
    put:
      summary: Updates a board
      tags:
      - Boards
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: board updated
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                name:
                  type: string
              required:
              - name
    delete:
      summary: Deletes a board
      tags:
      - Boards
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: board deleted
        '404':
          description: board not found
  "/api/v1/boards/{board_id}/columns":
    get:
      summary: Retrieves the columns of a board
      tags:
      - Columns
      parameters:
      - name: board_id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: columns retrieved
        '404':
          description: not found
    post:
      summary: Creates a column
      tags:
      - Columns
      parameters:
      - name: board_id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: column created
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
              required:
              - name
  "/api/v1/boards/{board_id}/columns/{id}":
    get:
      summary: Retrieves a column
      tags:
      - Columns
      parameters:
      - name: board_id
        in: path
        required: true
        schema:
          type: string
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: column found
        '404':
          description: not found
    put:
      summary: Updates a column
      tags:
      - Columns
      parameters:
      - name: board_id
        in: path
        required: true
        schema:
          type: string
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: column updated
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
              required:
              - name
    delete:
      summary: Deletes a column
      tags:
      - Columns
      parameters:
      - name: board_id
        in: path
        required: true
        schema:
          type: string
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: column deleted
        '404':
          description: column not found
  "/api/v1/boards/{board_id}/columns/{column_id}/stories":
    get:
      summary: Retrieves stories
      tags:
      - Stories
      parameters:
      - name: board_id
        in: path
        required: true
        schema:
          type: string
      - name: column_id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: stories retrieved
        '404':
          description: not found
    post:
      summary: Creates a story
      tags:
      - Stories
      parameters:
      - name: board_id
        in: path
        required: true
        schema:
          type: string
      - name: column_id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: story created
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
              required:
              - name
  "/api/v1/boards/{board_id}/columns/{column_id}/stories/{id}":
    get:
      summary: Retrieves a story
      tags:
      - Stories
      parameters:
      - name: board_id
        in: path
        required: true
        schema:
          type: string
      - name: column_id
        in: path
        required: true
        schema:
          type: string
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: story found
        '404':
          description: not found
    put:
      summary: Updates story
      tags:
      - Stories
      parameters:
      - name: board_id
        in: path
        required: true
        schema:
          type: string
      - name: column_id
        in: path
        required: true
        schema:
          type: string
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: story created
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
              required:
              - name
    delete:
      summary: Deletes a story
      tags:
      - Stories
      parameters:
      - name: board_id
        in: path
        required: true
        schema:
          type: string
      - name: column_id
        in: path
        required: true
        schema:
          type: string
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: column deleted
        '404':
          description: column not found
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000/
