default: &default
  adapter: mysql2
  username: root
  password: 2399
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  username: root
  password: 2399
  database: trello_test

test:
  <<: *default
  username: root
  password: 2399
  database: trello_test

production:
  <<: *default
  username: root
  password: 2399
  database: trello_test
